spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://youresbuddies:fmcS8QLnxt85ZBDh@cluster1.lwkedfx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1&tls=true
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true